[package]
name = "rust-actix"
version = "0.1.0"
authors = ["vomelchenko <v.omelchenko@smartweb.com.ua>"]
edition = "2018"

[dependencies]
bytes = "0.4.0"
openssl = "0.10.22"
actix-web = { version = "1.0.0-beta.2", features=["rust-tls", "ssl"] }
