[package]
name = "rust_sendfile"
version = "0.1.0"
authors = ["vomelchenko <v.omelchenko@smartweb.com.ua>"]
edition = "2018"

[dependencies]
futures = "0.1.2"
tk-sendfile = "0.4.0"
tokio-core = "0.1.6"
futures-cpupool = "0.1.2"

