http:
  host: 0.0.0.0
  port: 80

ssl:
  enabled: true
  host: 0.0.0.0
  port: 443
  cert_path: ssl/cert.pem
  key_path: ssl/key.pem

runtime:
  workers: 4
  max_memory_size: 1000  # in Mb

content:
  root_path: .

  files:
    /med.txt:
      path: /data/med.txt
      in_memory: true
    /small.txt:
      path: /data/small.txt
      in_memory: true
    /mbiged.txt:
      path: /data/big.txt
      in_memory: true

